name: Typecheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout

jobs:
  lint:
    timeout-minutes: 10
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Authenticate with private NPM for installing @sanity/sanitype
        run: pnpm config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_SANITYPE_TOKEN}}

      - name: Install dependencies
        run: pnpm install

      - name: Typecheck
        id: typecheck
        run: |
          node -v
          pnpm run typecheck
          pnpm run typecheck:examples
